name: Security scanning Golang and Docker files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-security:
    name: Go Static Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run GoSec security scan
        uses: securego/gosec-action@v2
        with:
          args: ./...

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

  docker-scan:
    name: Trivity based Docker image security scan
    runs-on: ubuntu-latest
    needs: go-security
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-uptime-monitor:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-uptime-monitor:latest
