name: Security scanning Golang and Docker files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-scan:
    name: Trivy based Docker image security scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-uptime-monitor:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-uptime-monitor:latest
